name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Test, and Run CLI Commands
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20' # Specify the Go version you want to use

      # Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install dependencies
      - name: Install dependencies
        run: go mod download

      # Run tests
      - name: Run tests
        run: go test -v ./...

      # Build the application
      - name: Build application
        run: go build -o app ./cmd/app # Adjust path to your main package if needed

      # Test the `list -a` command
      - name: Test `list -a` command
        run: |
          ./app list -a | tee list_a_output.txt
          echo "Output of 'list -a' command:"
          cat list_a_output.txt

          # Define the expected output
          expected_output=$(cat <<'EOF'
ID  Task                                         Created     Done
1)  Go to the store for milk.                    3 days ago  true
2)  Read a book.                                 2 days ago  true
3)  Set the trash out front.                     2 days ago  false
4)  Reset the alarm for earlier time to wakeup.  2 days ago  true
5)  Put laundry in the wash .                    a day ago   true
6)  Meal plan for the coming two weeks.          a day ago   false
EOF
          )

          # Validate the output
          if [[ "$(cat list_a_output.txt)" == "$expected_output" ]]; then
            echo "List -a command output is as expected."
          else
            echo "List -a command output is not as expected."
            echo "Expected:"
            echo "$expected_output"
            echo "Actual:"
            cat list_a_output.txt
            exit 1
          fi
