name: Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags, e.g., v1.0.0

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      # Build the application
      - name: Build application
        run: go build -o task

      # Create a GitHub Release and upload the binary
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: task # Specify the file to upload as a release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
